### ISSUE TITLE
Move session list sorting logic to the presentation layer

### ISSUE THREAD

**Issue by rodrigoperazzo** [DiscordTime/sticky-sessions-android#143]
Today's implementation sorts the list of sessions on the data layer, but it should be a task for the presenter. 

To make that, the domain model should change too since it is already receiving a converted string from the data layer. Possible impact on the adapter and classes depending on the session model.

**Comment by viniciusalbuquerque** [comment]
We have an issue opened about sorting by timestamp on server-side. Problem is we decided not to go through with the Pull-request because it would be better to put another parameter to the session when it's created to define the date that the session would happen.

Until now we were assuming that the date of creation was the date and time of the session. We need to implement that both sides (client and server).

**Comment by rodrigoperazzo** [comment]
I think it should be done on server-side indeed. Let's go back to that discussion, we should include on PR changing the session/meeting model to have two dates. DiscordTime/sticky-sessions-server#46
