### ISSUE TITLE
Create Firebase connection

### ISSUE THREAD

**Issue by ehammo** [DiscordTime/sticky-sessions-android#21]
Subtask of #2

**Comment by rodrigoperazzo** [comment]
In order to get most benefits from RX, I think we should do our operations using transactions (ref: https://firebase.google.com/docs/database/android/read-and-write?hl=pt-br#save_data_as_transactions) and convert to a Single (similar to was done here: https://github.com/FrangSierra/RxFirebase/blob/master/app/src/main/java/durdinapps/rxfirebase2/RxFirebaseDatabase.java).

**Comment by rodrigoperazzo** [comment]
Not a valid issue anymore. We decided to move to Retrofit.
